### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by 1AoB** [swharden/ABF-SDK#1]
Is there a C++ library that can replace Pyabf?

I'd appreciate any help.

**Comment by swharden** [comment]
Yes! That is here https://github.com/swharden/ABF-SDK/tree/main/ABFFIO-2.2.0.1

It is not open source but the header file is available.

Also check out AbfSharp, a C# interface for ABF files

Hope it helps!
Scott

**Comment by 1AoB** [comment]
![image](https://github.com/user-attachments/assets/8cdc8473-5210-4e33-b713-ee39de365813)

Dear Dr. Scott,

Thank you very much for your reply. After testing "https://github.com/swharden/ABF-SDK/tree/main/ABFFIO-2.2.0.1", the provided ABFFIO.dll is based on x86 architecture, and I hope it can run in x64 environment in Win11.
I would greatly appreciate it if you could provide ABFFIO.dll in the x64 architecture. If not, I will try using C # instead of pyabf. My goal is to reduce the size of the program. pyabf is a very good library file, but Python takes up too much space. I hope to minimize the size of the program as much as possible.

Many thanks for your time and advice.

**Comment by swharden** [comment]
Hi @1AoB,

Indeed, it is x86. It works on Windows 11.

It is proprietary, provided by Axon, and a 64-bit version is unlikely to be made, but as long as the app you develop targets x86 it can be used well.

I agree that Python (and all the crazy libraries) is HUGE and very difficult to deploy. I really enjoy creating C# apps with AbfSharp, because I can send somebody a very small EXE that they can double-click and it launches without trouble, allowing them to analyze their ABFs

It's a really minimal example, but https://github.com/swharden/ABFview (https://swharden.com/software/ABFview/) is such a program. It's a few years old and AbfSharp has been updated since then, so it may be a good idea for me to create a new minimal ABF browser demo and include it in the main AbfSharp repository.

Hope it helps!
